name: Build Azure Image with Packer

on: [push]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.1
      with:
        packer-version: 'v1.10.0'
    
    - name: Build Image
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      run: |
        packer build 
          -var 'client_id=${{ env.CLIENT_ID }}' \
          -var 'client_secret=${{ env.CLIENT_SECRET }}' \
          -var 'tenant_id=${{ env.TENANT_ID }}' \
          -var 'subscription_id=${{ env.SUBSCRIPTION_ID }}' \
           azure-packer-template.json
