name: Packer Build

on:
  push:
    branches:
      - main  # Set this to the branch that should trigger the build

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set Up Packer
      uses: hashicorp/setup-packer@v1.0.1
      with:
        packer-version: '1.6.0' # Specify the Packer version

    - name: Build Azure Image with Packer
      run: |
        packer build -var 'client_id=${{ secrets.AZURE_CLIENT_ID }}' \
                     -var 'client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' \
                     -var 'tenant_id=${{ secrets.AZURE_TENANT_ID }}' \
                     -var 'subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
                     template.json
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
