name: Build Azure Image with Packer

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: /home/osanda/actions-runner/_work/PackerImageBuild/PackerImageBuild

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.1
      with:
        packer-version: 'v1.10.0'
    
    - name: Build Image
      run: |
        packer build /home/osanda/Downloads/Packer-in-Azure-main/ubuntu.json
