name: Build Azure Image with Packer

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: /home/osanda/actions-runner/_work/PackerImageBuild/PackerImageBuild

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.1
      with:
        packer-version: 'v1.10.0'
    
    - name: Build Image
      run: |
        packer build /home/osanda/Downloads/Packer-in-Azure-main/ubuntu.json

    - name: Update scale set image
      run: |
        # Read secrets from file
        source /home/osanda/Downloads/Packer-in-Azure-main/secrets.txt

        # Login to Azure CLI using service principal credentials
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

        # Gather information about the built image to use in VMSS
        $imageId = $(az image show \
          --resource-group "cicd-project" \
          --name "myNewtest3PackerImage" \
          --query 'id' -o tsv)

        # Update the VMSS with the new image
        az vmss update \
          --resource-group " TEST4_GROUP" \
          --name "test4" \
          --set virtualMachineProfile.storageProfile.imageReference.id=$imageId
