name: Build Azure Image with Packer

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: /home/osanda/actions-runner/_work/PackerImageBuild/PackerImageBuild

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.1
      with:
        packer-version: 'v1.10.0'
    
    - name: Build Image
      run: |
        packer build /home/osanda/Downloads/Packer-in-Azure-main/ubuntu.json

    - name: Update scale set image
      # Adding 'env' to provide access to secrets, you must store your Azure credentials in GitHub secrets.
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: |
        # Login to Azure CLI using service principal credentials
        az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

        # Gather information about the built image to use in VMSS
        $imageId = $(az image show \
          --resource-group "cicd-project" \
          --name "NewTestImage" \
          --query 'id' -o tsv)

        # Update the VMSS with the new image
        az vmss update \
          --resource-group "YourScaleSetResourceGroup" \
          --name "YourScaleSetName" \
          --set virtualMachineProfile.storageProfile.imageReference.id=$imageId

